### ISSUE TITLE
F-46 Al crear un nuevo departamento genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/siaddhh#46]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-10-17 17-00-20](https://user-images.githubusercontent.com/10052756/137646849-1b016978-8ef4-431e-87bf-e8d2a95f1d84.png)

**Comment by pmartinez5** [comment]
P-U F-46 Probar en sitio de desarrollo si la falla se vuelve a presentar
Permite crear un nuevo departamento y volverlo a eliminar[
![FireShot Capture 347 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146308404-376e759d-e7d7-431e-b8d2-854752fcd61a.png)
](url)[
![FireShot Capture 348 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146308445-4326c709-b142-47f7-8b4a-d1b8ae43a5ff.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 10-43-38](https://user-images.githubusercontent.com/10052756/146681271-f32595a9-2063-4d8c-b700-d0723c83ec51.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 10-45-19](https://user-images.githubusercontent.com/10052756/146681335-5f5a354a-7ac7-4cc9-ac16-f942f74dd73b.png)
