### ISSUE TITLE
F-48 En el sitio dedesarrolo al filtrar por fecha en Conteo de victimizaciones individuales, no genera el mapa.

### ISSUE THREAD

**Issue by pmartinez5** [pasosdeJesus/siaddhh#48]
![FireShot Capture 007 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/137669215-7163bdcb-b00d-48d0-a638-6958b6c93728.png)

**Comment by vtamara** [comment]
Mapa se movió a menú propio.
