### ISSUE TITLE
F-50 Limitación a casos de asesinato para no autenticados debe hacerse al lado del servidor [0,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#50]

**Comment by vtamara** [comment]
Implementado

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 11-03-19](https://user-images.githubusercontent.com/10052756/146681805-517a1e29-6d4e-4db5-b755-5436b6d1bacf.png)
![Captura de pantalla de 2021-12-19 11-03-51](https://user-images.githubusercontent.com/10052756/146681807-22d8e3cf-4d20-45f5-8a92-2e09aaf9d931.png)
