### ISSUE TITLE
F-54 En formulario de caso no autocompleta víctimas colectivas

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#55]
Problema de permisos.

**Comment by pmartinez5** [comment]
Sigue presentando la falla no autocompleta victima colectiva
[
![FireShot Capture 364 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146489408-cd2fbf38-0bdb-4187-86c7-b24739dcef44.png)
](url)

**Comment by pmartinez5** [comment]
Para poder eliminar victima colectiva hay que hacer doble clic
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146589812-dfb53da1-fe28-4410-861b-eafbc2beac62.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-24 19-44-16](https://user-images.githubusercontent.com/10052756/147375088-1ba26711-27c7-4486-8b6c-5d21fc64ae5a.png)
