### ISSUE TITLE
R-55 Activar bitácora por casos para autenticados y presentarla en el resumen de un caso para autenticados

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#60]

**Comment by vtamara** [comment]
Implementado

**Comment by vtamara** [comment]
![image](https://user-images.githubusercontent.com/701221/144949938-2c4aa73a-27b0-4d60-93ab-5dd50a879a48.png)

**Comment by pmartinez5** [comment]
P-U R-55 Probar desde sitio de desarrollo, desde resumen se puede ver bitacora.
[
![FireShot Capture 328 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146283928-e8560477-f8b6-46b1-9264-5f8dfd3fce8b.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 09-04-15](https://user-images.githubusercontent.com/10052756/146677680-4e317d3e-b691-4bc6-a5e0-8461801f47d3.png)

**Comment by BlancaInesAcosta** [comment]
PU-R-55  Probar  R-55, R-65, R-85, R-63, R-62, R-67, R-69, F46, F50  [1]
