### ISSUE TITLE
F-62 En listado de caso agrear filtro Editado por [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#62]

**Comment by vtamara** [comment]
Permite elegir uno o más de los usuarios y busca casos que en bitácora tengan entrada Editado por el usuario elegido.

**Comment by alejocruzrcc** [comment]
Prueba

https://user-images.githubusercontent.com/12545631/144705470-b3727802-c729-4a1c-b183-8525318da434.MOV

:

**Comment by vtamara** [comment]
Implementación inicial

**Comment by pmartinez5** [comment]
P-U R-62 Filtro Editado por 
[
![FireShot Capture 339 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146298451-e117368b-0902-4db6-9d49-fa0b6ee30246.png)
](url)
[
![FireShot Capture 341 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146298526-04b74662-e8a9-4bf4-ad9d-e99b1f76178e.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (10)](https://user-images.githubusercontent.com/61369119/146607420-7392a6ce-eed4-4a71-9ce0-a91bbca0150f.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 09-55-43](https://user-images.githubusercontent.com/10052756/146679521-8048badd-6fdc-4e9d-b352-480daa8e93dd.png)
