### ISSUE TITLE
F-63 En listado de bitácoras agregar filtros para todas las columnas (por ejemplo para buscar quien eliminó casos) [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#63]

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/144705387-d4a87ead-19b7-47d3-9747-8f5f9bb47c52.MOV

**Comment by vtamara** [comment]
Implementación inicial

**Comment by pmartinez5** [comment]
P-U R-63 Probar los filtros en menú Bitacoras, desde el sitio de desarrollo
[
![FireShot Capture 336 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146289747-31866c1a-1c24-428b-ad52-97e192939293.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146485350-d0e6421c-abed-4010-9f7b-c9f40687ba4b.jpg)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146486179-f5378774-85d8-4d89-b2b9-39f290af77c3.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (3)](https://user-images.githubusercontent.com/61369119/146486545-74ced6df-c97f-4dcb-bfbf-3d3dc6a08c6b.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (5)](https://user-images.githubusercontent.com/61369119/146487101-cd5426d6-6a61-4c6c-9b22-7d66ea282bbb.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (6)](https://user-images.githubusercontent.com/61369119/146487281-fc927908-e40e-4357-8cc9-dafc7c57e913.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 09-47-05](https://user-images.githubusercontent.com/10052756/146679223-dddbd850-b781-401f-bf10-83c782292f82.png)
