### ISSUE TITLE
R-64 Poner instrucciones para quienes no puedan ver mapa por problema de certificados raíces vencidos el 30.Sep.2021

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#64]

**Comment by vtamara** [comment]
Resuelto:

![image](https://user-images.githubusercontent.com/701221/143764846-645ab64f-34ae-482e-911b-8635da25f715.png)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 324 - Mapa de Asesinatos – Somos Defensores - somosdefensores org](https://user-images.githubusercontent.com/61369119/146282204-1b0c20fb-f6d1-4dcd-8ebe-2aabe1ce8600.png)
](url)

**Comment by pmartinez5** [comment]
P-U R-64 Se busca pagina web de somos defensores, para probar R-64[
![FireShot Capture 325 - Mapa de Asesinatos – Somos Defensores - somosdefensores org](https://user-images.githubusercontent.com/61369119/146282502-512f6b5f-1400-49fa-8fdf-8808a5b4d51c.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 08-38-03](https://user-images.githubusercontent.com/10052756/146676884-695e19e7-c925-47fd-88b7-c81ad00fa493.png)
