### ISSUE TITLE
R-65 Resumen de caso que sea reporte general ara usuarios autenticados y para no autenticados que sigan siendo reporte revista

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#65]

**Comment by vtamara** [comment]
Cuando un usuario autenticado ve el reporte general de un caso:

![image](https://user-images.githubusercontent.com/701221/144948804-15dc2887-df5a-417b-a55a-a11b99a4f927.png)

Cuando un usuario no autenticado lo ve en sitio público:
![image](https://user-images.githubusercontent.com/701221/144949838-5c531932-3870-46bf-8225-499b296a2f58.png)

**Comment by pmartinez5** [comment]
P-U R-65 Como se ve en sitio de desarrollo
[
![FireShot Capture 331 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146286566-ff9eafe1-4e3f-4f0c-91db-0975b97c32e9.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 366 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146602861-96a5139a-cbf4-4d0e-8be2-1e31ccbf30df.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 09-14-54](https://user-images.githubusercontent.com/10052756/146678076-d931c5e0-e5c6-464a-9336-f5aa526f643f.png)
