### ISSUE TITLE
R-67 En mapa de calor agregar filtro de selección múltiple por categoría [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#67]

**Comment by vtamara** [comment]
Movido a https://github.com/pasosdeJesus/sivel2_gen/issues/600

**Comment by vtamara** [comment]
![Uploading screencapture-rbd-nocheyniebla-org-15443-somosdefensores-siaddhh-mapadep-victimizaciones-2021-12-06-19_46_37.png…]()

**Comment by pmartinez5** [comment]
P-U R-67 Probar filtro de selección multiple por categoria
[
![FireShot Capture 343 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146303481-d75abd6c-890b-4ce5-8883-ac630c1922e2.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 345 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146304854-09cf8135-50dc-427b-a034-4ff03b9ec322.png)
](url)

**Comment by pmartinez5** [comment]
Prueba
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146482628-193a6ee8-28f3-4c9e-909b-dab7734537e8.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (1)](https://user-images.githubusercontent.com/61369119/146483114-7b4b1c83-7050-41dd-8732-45a9d53825d5.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146610096-3f3e2f65-7bdd-417d-835e-43ea68d1be37.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 10-12-54](https://user-images.githubusercontent.com/10052756/146680178-808af42b-8207-401d-ba99-ca51e008afad.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 10-17-31](https://user-images.githubusercontent.com/10052756/146680347-705bc3c3-2148-49bf-ab58-16892155a02c.png)
Algunos
