### ISSUE TITLE
R-69 En conteo de victimizaciones individuales, filtro por categoría que además del texto que tenga el código. Con botones agregar todas, quitar todas y que limite a las categorias del tipo elegido (o todas si no se elige tipo) [3,4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#69]

**Comment by vtamara** [comment]
Avance con https://github.com/pasosdeJesus/siaddhh/pull/78

**Comment by vtamara** [comment]
No filtra la categoría elegida.  En el pantallazo siguiente debería limita categorías contadas a A10
![screencapture-rbd-nocheyniebla-org-3600-somosdefensores-siaddhh-conteos-victimizaciones-2021-12-02-04_42_27](https://user-images.githubusercontent.com/701221/144397207-5a42cb73-3aa1-4b68-8937-adb674c834f4.png)

**Comment by alejocruzrcc** [comment]
Más arreglos: 

https://user-images.githubusercontent.com/12545631/144705492-7f6e49f9-5284-4cbb-ac6a-83c5533bc1ff.MOV

**Comment by vtamara** [comment]
Mejorada con https://github.com/pasosdeJesus/siaddhh/commit/17e3d0074eef0bec92f3466ad248352d0d448e98 
https://github.com/pasosdeJesus/siaddhh/commit/a7a7c79baa4fbac7ccb1008e4e188c2919616336
y
https://github.com/pasosdeJesus/siaddhh/commit/e2d538fb455625bb9105fe7d964231f9b55b79ba

**Comment by pmartinez5** [comment]
P-U R-69 probar los botones Todas, ninguna, Algunas en filtro categoria 
[
![FireShot Capture 344 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146304616-ae3bfa74-047e-424b-a276-28fda74b44b2.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (2)](https://user-images.githubusercontent.com/61369119/146483740-7e9995fd-242b-415a-bbd0-e9b2ede4b79d.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (3)](https://user-images.githubusercontent.com/61369119/146484059-5f80d32e-3ff6-4608-8f93-33e9603cf947.png)
](url)

**Comment by BlancaInesAcosta** [comment]
En el sitio de pruebas no esta el botón
![Captura de pantalla de 2021-12-19 10-26-17](https://user-images.githubusercontent.com/10052756/146680663-3e95fdee-188f-4d02-9712-af3ae9aa49ea.png)
