### ISSUE TITLE
R-70 En mapa sobre openstreetmap, dejar los 5 filtros en la primera fila, y en la segunda el botón filtrar,  número y descargar [0,4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#70]

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/siaddhh/pull/76

**Comment by pmartinez5** [comment]
P-U R-70 probar en sitio de desarrollo que los filtros esten en la primera fila, en la segunda boton Filtrar, número y descargar.
[
![FireShot Capture 323 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146277563-01199c5e-f148-4a48-8a9c-9f1c634df9b2.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (8)](https://user-images.githubusercontent.com/61369119/146488479-d2705a8a-0c3c-4a76-b45d-bdae41a41496.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 08-35-32](https://user-images.githubusercontent.com/10052756/146676784-5f74c76e-ba74-4142-8b06-0167e9f1b137.png)
