### ISSUE TITLE
R-71 En mapa de casos color de fondo de filtros naranja [0,2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#71]

**Comment by vtamara** [comment]
Intento con https://github.com/pasosdeJesus/siaddhh/pull/76

**Comment by pmartinez5** [comment]
P-U R-71 Probar en sitio de desarrollo, Que los fondos de filtros sean de color naranja
[
![FireShot Capture 318 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146274825-d2e7f175-fef7-4106-a327-f7c2064e666c.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 08-34-00](https://user-images.githubusercontent.com/10052756/146676735-06b1cb09-f94f-43b9-a9b8-08eb968f7f2a.png)
