### ISSUE TITLE
R-72 Numero de casos quitar adminración después de mostrados.

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#72]

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (7)](https://user-images.githubusercontent.com/61369119/146487927-32be03fd-0198-4949-ac70-6579af99cff3.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 08-32-37](https://user-images.githubusercontent.com/10052756/146676686-7755477d-5fb2-45d0-adc4-f0a1c3c4d642.png)
