### ISSUE TITLE
R-73 Centrar el mapa

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#73]

**Comment by pmartinez5** [comment]
P-U R-73 
[
![FireShot Capture 313 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146270110-a77de296-ed4f-4ce7-ad1d-8dabd6e29044.png)
](url)

**Comment by pmartinez5** [comment]
P-U R-73 probar en el sistema de desarrollo, el mapa se ve centrado, se realiza filtro desde Conteo de victimizaciones individuales, por profesión, luego se mira en el menú mapa de victimizaciones por departamento. Se visualiza mapa
![Uploading FireShot Capture 315 - SIADDHH 2.1a1 - rbd.nocheyniebla.org.png…]()

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (4)](https://user-images.githubusercontent.com/61369119/146484378-a34cefc5-45bd-444b-b955-bf63595f6041.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 08-30-46](https://user-images.githubusercontent.com/10052756/146676627-f228afbe-3d32-4032-b83e-d0386952fa38.png)
