### ISSUE TITLE
R-74 En menú de página de somos defensores entre Informe y Actualidad nuevo menú "Mapa de asesinatos"

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#74]

**Comment by pmartinez5** [comment]
P-U R-74 Se busca la pagina Web de Somos Defensores para probar R-74
[
![FireShot Capture 326 - Somos Defensores – Programa Somos Defensores - somosdefensores org](https://user-images.githubusercontent.com/61369119/146282984-37c65272-e3ca-4a34-8301-32f933723d5f.png)
](url)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-12-19 08-28-32](https://user-images.githubusercontent.com/10052756/146676565-42d76dd3-63d6-4c13-af25-17c83e1c7071.png)
