### ISSUE TITLE
R-85 Desde listado de casos habilitar reporte revista y que tenga un formato de prediagramación de la publicación 

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/siaddhh#85]

**Comment by vtamara** [comment]
1. Filtrar a los casos por incluir en reporte
2. Elegir Reporte Revista
![ScreenShot Tool -20211206201925](https://user-images.githubusercontent.com/701221/144948457-82006f06-4455-47cd-abbe-289cc2b5b27c.png)
3. Presionar el botón Generar
![image](https://user-images.githubusercontent.com/701221/144948596-4d42b8a2-5550-4045-a120-0baaecf2b4bd.png)

**Comment by pmartinez5** [comment]
P-U siguiendo los tres pasos, pero no se visualiza ninguna foto en sitio de desarrollo
[
![FireShot Capture 333 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146288123-c6c7e247-667f-4ca3-9cef-bd83865494f9.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 334 - Reporte Revista - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146288183-8edc4678-063f-4ccc-af57-756725715418.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 367 - Reporte Revista - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146604272-55a3b7e6-893c-45ef-a81e-10aea34f8134.png)
](url)

**Comment by BlancaInesAcosta** [comment]
PU-R-55  Probar  R-55, R-65, R-85, R-63, R-62, R-67, R-69, F46, F50  [1]
![Captura de pantalla de 2021-12-19 09-26-30](https://user-images.githubusercontent.com/10052756/146678678-734f8755-6b6e-4713-b14e-467b8b82a14a.png)
![mujer](https://user-images.githubusercontent.com/10052756/146679029-408c1a84-04a4-4820-b907-08a5f5131850.jpeg)
